### PR TITLE
Dev elastic

### PR DESCRIPTION
**Pull request by montoyjh**
Updated the elastic workflow to allow for custom k-points.

### CODE REVIEW

**Comment by matk86** [comment]
Hi Joey,
just saw your pull request to pymatgen. If you could add the volume dependent  debye temperature formulation as mentioned in [http://doi.org/10.1016/j.comphy.2003.12.001](url) we could easily extend your elasticity workflow(add one more task) to compute the gibbs free energy using the quasi harmonic debye model mentioned in the aforementioned paper. This would much more cheaper than computing the free energy from the full phonon spectrum.

**Comment by montoyjh** [comment]
Sure, is this just the expression in equations 6-7 of that paper?

-Joey

**Comment by matk86** [comment]
yes, but i am not sure how reliable those equations are ..the author cites his thesis as the reference but i couldnt find it..

**Comment by montoyjh** [comment]
I've added it and a unit test (I get a reasonable number for the test
structure, Tin (around 189 K), but I'm really not confident that what I did
was correct, so we should test it more thoroughly before using it in
production.

**Comment by matk86** [comment]
Sure, thanks

**Pull request merged**
