### PR TITLE
Fixing small typos.

### PR DESCRIPTION
**Pull request by albalu**
Fixing some small typos as I read through the documentation.

### CODE REVIEW

**Comment by computron** [comment]
See this:
https://www.quora.com/Is-softwares-a-correct-English-word

**Comment by albalu** [comment]
Ah, thanks! so it was just one extra "makes".

**Comment by computron** [comment]
(if it bothers you, you can switch it to "software packages") - let me know when ready

**Comment by albalu** [comment]
No it doesn't bother me but please leave this merge request open for today as I may find a few more. I will just comment "ready" later.

**Comment by albalu** [comment]
ready.

**Comment by computron** [comment]
Thanks!

**Pull request merged**
