### PR TITLE
Raman Workflow

### PR DESCRIPTION
**Pull request by matk86**
## Summary

* Compute Raman susceptibility tensor.
* For each phonon mode the Raman susceptibility tensor = First derivative of the dielectric tensor wrt the atomic displacement along that mode([10.1103/PhysRevB.73.104304](http://journals.aps.org/prb/abstract/10.1103/PhysRevB.73.104304))
* tested on matgen

### CODE REVIEW

**Comment by computron** [comment]
Thanks! Can you add some basic unit tests before I merge?

**Comment by matk86** [comment]
sure

**Comment by matk86** [comment]
added full raman wflow test using runvaspfake

**Comment by computron** [comment]
Thanks! But are all these files necessary? There are some fairly large ones in there (and unzipped)

**Comment by matk86** [comment]
cleaned up the test files folder: removed unnecessary ones and zipped vasprun/outcar files

**Comment by computron** [comment]
Thanks!

**Comment by computron** [comment]
@matk86 - please remember to delete the "raman" branch if finished

**Pull request merged**
