### PR TITLE
Split VaspToDbTaskDone into VaspDrone + Database.

### PR DESCRIPTION
**Pull request by matk86**
## Summary

Split `vasp.drones.VaspToDbTaskDrone` into Drone + Database.

* add `vasp.database.py` module. The `MMDb` class encapsulates the database connections and operations such as building the indices, doc insertion into mongodb and GridFS
* add `VaspDrone` to `vasp.drones.py`. The old one retained(renamed as `VaspToDbTaskDone_to_remove`). The new drone sticks to the basic definition of the drone, just assimilates the calculations directory and returns the task document.
* updated `VaspToDbTask` firetask in `firetasks.parse_outputs.py`. Added 'db_build' and 'db_indices' optional keys. The old one retained as `VaspToDbTask_to_remove`

## TODO 

* Update `ToDbTask`. The db insertion part from the new `VaspToDbTask` can be moved to `ToDbTask`.
* Add firetask to build index

### CODE REVIEW

**Comment by computron** [comment]
Although I like having an MMDB class to manage the tasks database, I don't think this refactoring maintains the contract of a Drone. i.e., the assimilate() method is supposed to insert a document into the database according to AbstractDrone. This is so that the "hive"/"queen" stuff can efficiently take in a Drone and create a vasp database.

I would either fulfill the contract of a Drone, or don't call it a drone ...

**Comment by matk86** [comment]
database insertion is not mentioned in the abstractdrone's assimilate

**Comment by matk86** [comment]
any MSONable object will do

**Comment by computron** [comment]
ok I just checked again, you are correct

**Comment by computron** [comment]
There is a lot of stuff about "VaspToDbTaskDrone_to_remove()". Can you instead just finalize all the changes to what you think it should be in the end?

**Comment by matk86** [comment]
removed all *_to_remove stuff and updated the ToDbTask

**Comment by computron** [comment]
Thanks!

**Pull request merged**
